import { ChatPromptTemplate } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { getLLM } from "../llm.js";
import { logger } from "../utils/logger.js";

const llm = getLLM();

const writerPrompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    `You are a Professional Report Writer Agent. Your job is to take raw research findings and fact-check results, then produce a polished, publication-ready research report.

FORMAT REQUIREMENTS:
# [Descriptive Report Title]

## Executive Summary
A concise 2-3 sentence overview of the most important findings.

## Key Findings

### [Finding 1 Title]
Detailed explanation with in-text citations [1]. Every factual claim must reference a source using [N] notation, where N maps to the Sources section below.

### [Finding 2 Title]
Continue with more findings [2][3]...

(Include 3-5 key findings based on available research)

## Fact-Check Summary
Brief summary of verification results — what was confirmed, what needs caution.

## Sources
[1] [Source Title](URL)
[2] [Source Title](URL)
...

## Conclusion
Final synthesis and forward-looking perspective.

---
*Report generated by Multi-Agent Research System*

CRITICAL RULES:
- EVERY factual claim MUST have an inline citation [N]
- Source numbers [N] must map exactly to the Sources section
- Use Markdown formatting throughout (headings, bold, lists)
- Keep language professional but accessible
- Do NOT invent any information — only use what is provided
- Preserve ALL source URLs from the research
- If fact-check flagged something as unverified, mention it with a caveat`,
  ],
  [
    "human",
    `Write a structured research report based on the following:

## Research Data:
{research_data}

## Fact-Check Results:
{fact_check_results}

## Original Sources Found:
{sources_list}`,
  ],
]);

const writerChain = writerPrompt.pipe(llm).pipe(new StringOutputParser());

export async function writerNode(state) {
  logger.agentStart("Writer Agent");

  const sourcesFormatted = state.sources
    .map((s, i) => `[${i + 1}] ${s.url}`)
    .join("\n");

  const report = await writerChain.invoke({
    research_data: state.researchData,
    fact_check_results: state.factCheckResults,
    sources_list: sourcesFormatted || "No specific sources extracted",
  });

  logger.agentEnd("Writer Agent");

  return {
    finalReport: report,
    currentAgent: "done",
    progressEvents: [
      {
        type: "progress",
        agent: "writer",
        message: "Report written — research complete!",
        timestamp: Date.now(),
      },
    ],
  };
}
